@startuml AdjustPcb_StateMachine
!define DARKBLUE #0000A0
!define DARKGREEN #008000
!define DARKORANGE #FF8C00

skinparam state {
  BackgroundColor LightBlue
  BorderColor Black
  ArrowColor Black
}

skinparam ArrowThickness 1.1
skinparam StateBorderThickness 1.5
skinparam DefaultFontSize 12

title AdjustPcb State Machine Flow

[*] --> AdjustPcb

state AdjustPcb {
}

AdjustPcb --> PrepareScavenging : NextStep\n[ScavengerIsActive\nScavengingSelected]
AdjustPcb --> AdjustCrosshair : NextStep\n[IsDesolderSelected]
AdjustPcb --> PreparePickUpFromTray : NextStep\n[IsBigComponentSelected\nIsPlacementSelected]
AdjustPcb --> PrepareProvideComponent : NextStep\n[IsPlacementSelected]
AdjustPcb --> Inspection : NextStep\n[IsInspectionSelected]
AdjustPcb --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected]
AdjustPcb --> InspectionAfterSolder : NextStep\n[IsInspectionAfterSolderSelected]
AdjustPcb --> FinishRework : NextStep
AdjustPcb --> CanceledWorkflow : CancelRework

state PrepareScavenging {
}

PrepareScavenging --> AdjustTeSensor : NextStep\n[ScavengerIsActive\nScavengingSelected\nPrepareScavengingFinished]

state AdjustCrosshair {
}

AdjustCrosshair --> AdjustTeSensor : NextStep\n[AdjustDriveFinished]

state AdjustTeSensor {
}

AdjustTeSensor --> InsertScavengingPipette : NextStep\n[ScavengerIsActive\nScavengingSelected\nPrepareScavengingFinished]
AdjustTeSensor --> Desolder : NextStep\n[AdjustDriveFinished\nIsDesolderSelected]
AdjustTeSensor --> FinishRework : NextStep

state InsertScavengingPipette {
}

InsertScavengingPipette --> Desolder : NextStep\n[InsertScavengingPipetteFinished]

state Desolder {
}

Desolder --> ScavengingElement : NextStep\n[ScavengerIsActive\nScavengingSelected\nIsDesolderFinished]
Desolder --> CleanBoard : NextStep\n[IsDesolderFinished]
Desolder --> AdjustCrosshair : PreviousStep

state ScavengingElement {
}

ScavengingElement --> FinishedScavenging : NextStep\n[ScavengingElementFinished]

state FinishedScavenging {
}

FinishedScavenging --> PrepareProvideComponent : NextStep\n[IsPlacementSelected\nScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> PickUpFromTray : NextStep\n[IsPlacementSelected\nIsBigComponentSelected\nScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> Inspection : NextStep\n[IsInspectionSelected\nScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected\nScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> InspectionAfterSolder : NextStep\n[IsInspectionAfterSolderSelected\nScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> FinishRework : NextStep\n[ScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> MoveHeatingheadToTray : NextStep\n[ScavengingFinished]

state CleanBoard {
}

CleanBoard --> PreparePickUpFromTray : NextStep\n[IsBigComponentSelected\nIsPlacementSelected]
CleanBoard --> PrepareProvideComponent : NextStep\n[IsPlacementSelected]
CleanBoard --> Inspection : NextStep\n[IsInspectionSelected]
CleanBoard --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected]
CleanBoard --> InspectionAfterSolder : NextStep\n[IsInspectionAfterSolderSelected]
CleanBoard --> FinishRework : NextStep

state PreparePickUpFromTray {
}

PreparePickUpFromTray --> PickUpFromTray : NextStep\n[IsPreparePickUpFromTrayFinished]

state PickUpFromTray {
}

PickUpFromTray --> PrepareProvideComponent : NextStep\n[IsPickUpFromTrayFinished\nIsPlacementSelected\nIsBigComponentSelected]
PickUpFromTray --> PinDetection : NextStep\n[IsPickUpFromTrayFinished\nIsBigComponentSelected]

state PrepareProvideComponent {
}

PrepareProvideComponent --> ProvideComponent : NextStep

state ProvideComponent {
}

ProvideComponent --> PinDetection : NextStep\n[IsProvideComponentFinished]

state PinDetection {
}

PinDetection --> FindBestMatch : NextStep\n[IsPinDetectionFinished\nIsDesolderSelected]
PinDetection --> FindBestMatch : NextStep\n[IsCyclicWorkflowMode]
PinDetection --> AdjustCrosshairAfterProvideComponent : NextStep\n[IsPinDetectionFinished]

state AdjustCrosshairAfterProvideComponent {
}

AdjustCrosshairAfterProvideComponent --> FindBestMatch : NextStep\n[IsAdjustDriveAfterProvideFinished]

state FindBestMatch {
}

FindBestMatch --> AdjustBestMatch : NextStep\n[IsFindBestMatchFinished]

state AdjustBestMatch {
}

AdjustBestMatch --> PlaceComponent : NextStep\n[IsPinDetectionFinished]
AdjustBestMatch --> PlaceComponent : NextStep\n[IsAdjustDriveAfterProvideFinished]

state PlaceComponent {
}

PlaceComponent --> ProvideComponent : NextStep\n[IsPlaceComponentFinished\nIsCyclicWorkflowMode]
PlaceComponent --> Inspection : NextStep\n[IsPlaceComponentFinished\nIsInspectionSelected]
PlaceComponent --> Solder : NextStep\n[IsPlaceComponentFinished\nIsSolderSelected\nIsDesolderSelected]
PlaceComponent --> AdjustTeSensorForSolder : NextStep\n[IsPlaceComponentFinished\nIsSolderSelected]
PlaceComponent --> InspectionAfterSolder : NextStep\n[IsPlaceComponentFinished\nIsInspectionAfterSolderSelected]
PlaceComponent --> FinishRework : NextStep\n[IsPlaceComponentFinished]

state Inspection {
}

Inspection --> Solder : NextStep\n[IsSolderSelected\nIsDesolderSelected]
Inspection --> AdjustTeSensorForSolder : NextStep\n[IsSolderSelected\nIsPlacementSelected]
Inspection --> Solder : NextStep\n[IsSolderSelected\nIsPlacementSelected\nIsDesolderSelected]
Inspection --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected]
Inspection --> FinishRework : NextStep\n[IsInspectionAfterSolderSelected]
Inspection --> FinishRework : NextStep

state AdjustCrosshairForSolder {
}

AdjustCrosshairForSolder --> AdjustTeSensorForSolder : NextStep\n[IsAdjustDriveForSolderFinished]

state AdjustTeSensorForSolder {
}

AdjustTeSensorForSolder --> Solder : NextStep\n[IsSolderSelected]
AdjustTeSensorForSolder --> InspectionAfterSolder : NextStep\n[IsInspectionAfterSolderSelected]
AdjustTeSensorForSolder --> FinishRework : NextStep\n[IsSolderingFinished]

state Solder {
}

Solder --> InspectionAfterSolder : NextStep\n[IsSolderingFinished\nIsInspectionAfterSolderSelected]
Solder --> FinishRework : NextStep\n[IsSolderingFinished]

state InspectionAfterSolder {
}

InspectionAfterSolder --> FinishRework : NextStep

state MoveHeatingheadToTray {
}

MoveHeatingheadToTray --> PrepareProvideComponent : NextStep\n[IsPlacementSelected\nIsHeatingHeadDriveFinished]
MoveHeatingheadToTray --> PickUpFromTray : NextStep\n[IsPlacementSelected\nIsBigComponentSelected\nIsHeatingHeadDriveFinished]
MoveHeatingheadToTray --> Inspection : NextStep\n[IsInspectionSelected\nIsHeatingHeadDriveFinished]
MoveHeatingheadToTray --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected\nIsHeatingHeadDriveFinished]
MoveHeatingheadToTray --> InspectionAfterSolder : NextStep\n[IsInspectionAfterSolderSelected\nIsHeatingHeadDriveFinished]
MoveHeatingheadToTray --> FinishRework : NextStep\n[IsHeatingHeadDriveFinished]

state FinishRework {
}

state CanceledWorkflow {
}

note right of AdjustPcb
  Starting point of this workflow
end note

note right of FinishRework
  End point of workflow
end note


@enduml