@startuml
!define DARKBLUE #0000A0
!define DARKGREEN #008000
!define DARKORANGE #FF8C00
!define DARKRED #FF0000

skinparam state {
  BackgroundColor LightBlue
  BorderColor Black
  ArrowColor Black
}

skinparam ArrowThickness 1.1
skinparam StateBorderThickness 1.5
skinparam DefaultFontSize 12

[*] --> Undefined

state Undefined {
  [*] --> Idle
  Idle : Wait for user input
  Undefined --> Undefined : Logout
}

Undefined --> SelectProfile : NextStep

state SelectProfile {
  [*] --> SelectWorkflow
  SelectWorkflow : User selects workflow and profile
}

SelectProfile --> Undefined : Logout
SelectProfile --> AdjustPcb : NextStep\n[IsAlreadyReferenced\nProfileSelected\nExtendedHeatersActive]
SelectProfile --> PrepareScavenging : NextStep\n[IsAlreadyReferenced\nScavengerIsActive\nScavengingSelected]
SelectProfile --> AdjustCrosshair : NextStep\n[IsAlreadyReferenced\nIsDesolderSelected\nProfileSelected\nPcbFrameInLockPosition\n]
SelectProfile --> AdjustCrosshairForBigBGA : <color:red>NextStep\n<color:red>[IsAlreadyReferenced\n<color:red>ProfileSelected\n<color:red>IsUserDefindedPlacmentFilterSelected]
SelectProfile --> PreparePickUpFromTray : NextStep\n[IsAlreadyReferenced\nIsBigComponentSelected\nIsPlacementSelected\nPcbFrameInLockPosition\nProfileSelected]
SelectProfile --> ProvideComponent : NextStep\n[IsAlreadyReferenced\nIsCyclicWorkflowMode\nPcbFrameInLockPosition]
SelectProfile --> PrepareProvideComponent : NextStep\n[IsAlreadyReferenced\nIsPlacementSelected\nProfileSelected\nPcbFrameInLockPosition]
SelectProfile --> Inspection : NextStep\n[IsAlreadyReferenced\nIsInspectionSelected\nProfileSelected\nPcbFrameInLockPosition]
SelectProfile --> AdjustPcbForSolder : NextStep\n[IsAlreadyReferenced\nIsSolderSelected\nProfileSelected\nExtendedHeatersActive]
SelectProfile --> AdjustCrosshairForSolder : NextStep\n[IsAlreadyReferenced\nIsSolderSelected\nProfileSelected\nPcbFrameInLockPosition]
SelectProfile --> InspectionAfterSolder : NextStep\n[IsAlreadyReferenced\nIsInspectionAfterSolderSelected\nProfileSelected\nPcbFrameInLockPosition]
SelectProfile --> InsertScavengingPipette : NextStep\n[ScavengingSelected\nProfileSelected\nIsAlreadyReferenced]

AdjustPcb --> PrepareScavenging : NextStep\n[ScavengerIsActive\nScavengingSelected]
AdjustPcb --> AdjustCrosshair : NextStep\n[IsDesolderSelected]
AdjustPcb --> PreparePickUpFromTray : NextStep\n[IsBigComponentSelected\nIsPlacementSelected]
AdjustPcb --> PrepareProvideComponent : NextStep\n[IsPlacementSelected]
AdjustPcb --> Inspection : NextStep\n[IsInspectionSelected]
AdjustPcb --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected]
AdjustPcb --> InspectionAfterSolder : NextStep\n[IsInspectionAfterSolderSelected]
AdjustPcb --> FinishRework : NextStep

state "AdjustCrosshairForBigBGA" as AdjustCrosshairForBigBGA #red {
  [*] --> AdjustCrosshairForBigBGAProcess
  state "AdjustCrosshairForBigBGAProcess" as AdjustCrosshairForBigBGAProcess #red
  AdjustCrosshairForBigBGAProcess : Adjust crosshair for Big BGA
}

state "FourCornerRotationCorrection" as FourCornerRotationCorrection #red {
  [*] --> FourCornerRotationCorrectionProcess
  state "FourCornerRotationCorrectionProcess" as FourCornerRotationCorrectionProcess #red
  FourCornerRotationCorrectionProcess : Execute four corner rotation correction for Big BGA
}

state "FourCornerPinDetection" as FourCornerPinDetection #red {
  [*] --> FourCornerPinDetectionProcess
  state "FourCornerPinDetectionProcess" as FourCornerPinDetectionProcess #red
  FourCornerPinDetectionProcess : Execute four corner pin detection for Big BGA
}

AdjustCrosshairForBigBGA --> PreparePickUpFromTray : <color:red>NextStep\n<color:red>[InnerProcessFourPointMethodFinished]

AdjustCrosshair --> AdjustTeSensor : NextStep\n[AdjustDriveFinished]

AdjustTeSensor --> InsertScavengingPipette : NextStep\n[ScavengerIsActive\nScavengingSelected\nPrepareScavengingFinished]
AdjustTeSensor --> Desolder : NextStep\n[AdjustDriveFinished\nIsDesolderSelected]
AdjustTeSensor --> FinishRework : NextStep

InsertScavengingPipette --> Desolder : NextStep\n[InsertScavengingPipetteFinished]

Desolder --> ScavengingElement : NextStep\n[ScavengerIsActive\nScavengingSelected\nIsDesolderFinished]
Desolder --> CleanBoard : NextStep\n[IsDesolderFinished]
Desolder --> AdjustCrosshair : PreviousStep

ScavengingElement --> FinishedScavenging : NextStep\n[ScavengingElementFinished]

FinishedScavenging --> PrepareProvideComponent : NextStep\n[IsPlacementSelected\nScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> PickUpFromTray : NextStep\n[IsPlacementSelected\nIsBigComponentSelected\nScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> Inspection : NextStep\n[IsInspectionSelected\nScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected\nScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> InspectionAfterSolder : NextStep\n[IsInspectionAfterSolderSelected\nScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> FinishRework : NextStep\n[ScavengerOnlySelected\nScavengingFinished]
FinishedScavenging --> MoveHeatingheadToTray : NextStep\n[ScavengingFinished]

CleanBoard --> PreparePickUpFromTray : NextStep\n[IsBigComponentSelected\nIsPlacementSelected]
CleanBoard --> PrepareProvideComponent : NextStep\n[IsPlacementSelected]
CleanBoard --> Inspection : NextStep\n[IsInspectionSelected]
CleanBoard --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected]
CleanBoard --> InspectionAfterSolder : NextStep\n[IsInspectionAfterSolderSelected]
CleanBoard --> FinishRework : NextStep

PrepareScavenging --> AdjustTeSensor : NextStep\n[ScavengerIsActive\nScavengingSelected\nPrepareScavengingFinished]

PrepareProvideComponent --> ProvideComponent : NextStep

ProvideComponent --> PinDetection : NextStep\n[IsProvideComponentFinished]

PreparePickUpFromTray --> PickUpFromTray : NextStep\n[IsPreparePickUpFromTrayFinished]

PickUpFromTray --> PinDetection : NextStep\n[IsPickUpFromTrayFinished\nIsBigComponentSelected]
PickUpFromTray --> PrepareProvideComponent : NextStep\n[IsPickUpFromTrayFinished\nIsPlacementSelected\nIsBigComponentSelected]
PickUpFromTray --> FourCornerRotationCorrection : <color:red>NextStep\n<color:red>[IsPickUpFromTrayFinished\n<color:red>IsPlacementSelected\n<color:red>IsUserDefindedPlacmentFilterSelected]

FourCornerRotationCorrection --> FourCornerPinDetection : <color:red>NextStep\n<color:red>[IsFourCornerRotationCorrectionFinished]
FourCornerPinDetection --> PrepareProvideComponent: <color:red>NextStep\n<color:red>[IsPickUpFromTrayFinished\n<color:red>IsPlacementSelected\n<color:red>IsUserDefindedPlacmentFilterSelected]

PinDetection --> FindBestMatch : NextStep\n[IsPinDetectionFinished\nIsDesolderSelected]
PinDetection --> FindBestMatch : NextStep\n[IsCyclicWorkflowMode]
PinDetection --> AdjustCrosshairAfterProvideComponent : NextStep\n[IsPinDetectionFinished]

AdjustCrosshairAfterProvideComponent --> FindBestMatch : NextStep\n[IsAdjustDriveAfterProvideFinished]

FindBestMatch --> AdjustBestMatch : NextStep\n[IsFindBestMatchFinished]

AdjustBestMatch --> PlaceComponent : NextStep\n[IsPinDetectionFinished]
AdjustBestMatch --> PlaceComponent : NextStep\n[IsAdjustDriveAfterProvideFinished]

PlaceComponent --> ProvideComponent : NextStep\n[IsPlaceComponentFinished\nIsCyclicWorkflowMode]
PlaceComponent --> Inspection : NextStep\n[IsPlaceComponentFinished\nIsInspectionSelected]
PlaceComponent --> Solder : NextStep\n[IsPlaceComponentFinished\nIsSolderSelected\nIsDesolderSelected]
PlaceComponent --> AdjustTeSensorForSolder : NextStep\n[IsPlaceComponentFinished\nIsSolderSelected]
PlaceComponent --> InspectionAfterSolder : NextStep\n[IsPlaceComponentFinished\nIsInspectionAfterSolderSelected]
PlaceComponent --> FinishRework : NextStep\n[IsPlaceComponentFinished]

Inspection --> Solder : NextStep\n[IsSolderSelected\nIsDesolderSelected]
Inspection --> AdjustTeSensorForSolder : NextStep\n[IsSolderSelected\nIsPlacementSelected]
Inspection --> Solder : NextStep\n[IsSolderSelected\nIsPlacementSelected\nIsDesolderSelected]
Inspection --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected]
Inspection --> FinishRework : NextStep\n[IsInspectionAfterSolderSelected]
Inspection --> FinishRework : NextStep

AdjustPcbForSolder --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected]

AdjustCrosshairForSolder --> AdjustTeSensorForSolder : NextStep\n[IsAdjustDriveForSolderFinished]

AdjustTeSensorForSolder --> Solder : NextStep\n[IsSolderSelected]
AdjustTeSensorForSolder --> InspectionAfterSolder : NextStep\n[IsInspectionAfterSolderSelected]
AdjustTeSensorForSolder --> FinishRework : NextStep\n[IsSolderingFinished]

Solder --> InspectionAfterSolder : NextStep\n[IsSolderingFinished\nIsInspectionAfterSolderSelected]
Solder --> FinishRework : NextStep\n[IsSolderingFinished]

InspectionAfterSolder --> FinishRework : NextStep

MoveHeatingheadToTray --> PrepareProvideComponent : NextStep\n[IsPlacementSelected\nIsHeatingHeadDriveFinished]
MoveHeatingheadToTray --> PickUpFromTray : NextStep\n[IsPlacementSelected\nIsBigComponentSelected\nIsHeatingHeadDriveFinished]
MoveHeatingheadToTray --> Inspection : NextStep\n[IsInspectionSelected\nIsHeatingHeadDriveFinished]
MoveHeatingheadToTray --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected\nIsHeatingHeadDriveFinished]
MoveHeatingheadToTray --> InspectionAfterSolder : NextStep\n[IsInspectionAfterSolderSelected\nIsHeatingHeadDriveFinished]
MoveHeatingheadToTray --> FinishRework : NextStep\n[IsHeatingHeadDriveFinished]

state FinishRework {
  [*] --> CleanupAndFinalize
  CleanupAndFinalize : Cleanup and finalize workflow
}

FinishRework --> SelectProfile : NextStep
FinishRework --> SelectProfile : RedoRework
FinishRework --> SelectProfile : CancelRework

note right of Undefined
  Starting point of the workflow
end note

note right of FinishRework
  End point of any workflow
  Returns to SelectProfile
end note

@enduml