:toclevels: 4
:icons: font
:icon-set: fas
ifndef::imagesdir[:imagesdir: ./images]

// include version adoc
include::./generated/version.adoc[]

= System documentation

[NOTE]
====
This documentation has been generated by https://doctoolchain.org/docToolchain/v2.0.x/index.html[Doctoolchain]. 
If you like to change the documentation please use the source files.

The source files can be found in https://kurtzersamaschinen.visualstudio.com/iConNext/_git/EaaS.Tools.System.Documentation[Azure DevOps - EaaS.Tools.System.Documentation].
====

[TIP]
====
The diagrams included by this documentation do have the following git version (commit hash):
{git_version} 
====

[CAUTION]
====
The following documentation is not the result of the development but was created as follow-up documentation.
Therefore, not all design decisions are likely to be found in this document.

This is also the reason why the system and the software are all handled together in one architecture documentation.
====

// horizontal line
***

== System components and interfaces

image::export\drawio\component_SystemDiagram.drawio\System_i-Con_Next.svg[]

plantuml::system_use_cases\initialization\includes\actors\inc_sys_actors_detailed.puml["General-system-components-and-interfaces",format=svg]

=== Components

[#Component_i-Con_Trace_Device]
*[.underline]#Component i-Con Trace Device (System scope)#*

This component represents the soldering station subsystem. 
The component is responsible for the physical soldering task and the tool the user will use to realize the soldering point.

[#Component_Mobile_Application]
*[.underline]#Component Mobile Application (System scope)#*

This component represents the mobile application Ersa Trace. 
The mobile application offers the possibility to the user to control the component i-Con Trace Device and is mainly intended for the home user. 
The application shall allow following things:
    
  * Requesting information about ...
    - Station
    - Firmware
    - Network settings
    - Basic settings
  * Control station settings  ...
    - Temperature 
    - Temperature window (high/low)
    - Calibration settings
    - Standby settings
    - Power settings
    - Pins settings
  * Scan soldering material ...
    - Soldering tip

The mobile application is able to care for multiple devices.

[#Component_ETC_Application]
*[.underline]#Component ETC Application (System scope)#*

The component ETC application represents the professional trace solution for integration of multiple soldering stations into a manufacturing execution system (MES).
ETC is able to manage ...

  * different workplaces (soldering stations)
  * soldering accessories (materials)
  * soldering jobs 

ETC implements a user role system that allows different user groups to have different privileges.
ETC is also able to update the soldering stations and fully control them.

[#Component_MQTT_Broker]
*[.underline]#Component MQTT Broker (System scope)#*

The component MQTT Broker is a mqtt server instance that manages the communication between <<Component_ETC_Application>> and <<Component_i-Con_Trace_Device>>.

[#Component_Network]
*[.underline]#Component Network (out of system scope)#*

The network component represents the network connection between the different components.
In concrete terms the network component is about the cabling, routers, switches, access points, etc. and the configuration of all those parts of the network.
As every company has their own restrictions for their IT infrastructure the component network is outside of the system scope. 
But as the network has a big impact on the system it's necessary to take it to account.

[#Component_mains_power]
*[.underline]#Component mains power (out of system scope)#*

The component mains power represents the power supply that is also outside of the scope of this system.
But as the power supply has also a big impact on the system it's necessary being mentioned.
The component especially needs to be taken into account for the usage of the system in different countries.

=== Interfaces

[#Interface_traceMainsPower]
*[.underline]#Interface traceMainsPower#*

Supported are following mains voltages:

  * 230 V / 50 Hz
  * 110 V / 60 Hz

The **traceMainsPower** interface is responsible to support the component i-Con Trace Device with mains power.

__Link to detailed interface description:__ n.A.

[#Interface_traceNetwork]
*[.underline]#Interface traceNetwork#*

Supported are following network interfaces:

  * WLAN
  * optionally LAN

The **traceNetwork** interface is responsible to support the connection into a network.

__Link to detailed interface description:__ 

* link:https://ersa.atlassian.net/wiki/spaces/IC/pages/1854996481/mDNS+Communication[MDNS]
* link:https://ersa.atlassian.net/wiki/spaces/IC/pages/1825243178/Ersa-Protocol[Ersa Protocol]
* link:https://ersa.atlassian.net/wiki/spaces/IC/pages/1854898177/MQTT+Communication[MQTT]

[#Interface_traceBlue_mobileBlue]
*[.underline]#Interface traceBluetooth / mobileBluetooth#*

The **traceBluetooth** interface is responsible to support the connection via bluetooth. 
The interface is been used by <<Component_Mobile_Application>> for initial setup of WLAN configuration.

__Link to detailed interface description:__ 

* link:https://ersa.atlassian.net/wiki/spaces/IC/pages/2200207461/Bluetooth[Bluetooth]

[#Interface_traceUI]
*[.underline]#Interface traceUI#*

The **traceUI** interface is responsible for the user interaction.
In case of the i-Con Trace Device the user is able to directly interact with following elements:

  * 3 LEDs:
    - ONLINE Led: representing network status
    - READY Led: representing soldering iron status
    - SERVICE Led: representing service status
  * Reset Button:
    - Offer the possibility to reset the network settings

__Link to detailed interface description:__ 

* link:++file:///L:/TDWEB/TDWeb_EPM/Software/TRACE-Cockpit/Offizielle Releases - Ersa TRACE Cockpit/++[ETC Releases] - find the manual within every release

[#Interface_mobileUI]
*[.underline]#Interface mobileUI#*

The **mobileUI** interface is responsible for the user interaction with the mobile phone to control the i-Con Trace Device.
The user has the ability to get a lot more information about the i-Con Trace Device in contrast to the direct <<Interface_traceUI>>.
The possibilities are listed within <<Component_Mobile_Application>>.

__Link to detailed interface description:__ n.A.

(The mobile app UI is designed intuitive and easy to use. A UI description is not available because of this reason.)

[#Interface_mobileNetwork]
*[.underline]#Interface mobileNetwork#*

As the <<Component_Mobile_Application>> runs on a mobile device the normal network interface is limited to WLAN.
In some cases it's possible the device uses LAN via specific adapters.
From the networks perspective it doesn't make any difference.

The **mobileNetwork** interface is responsible to support the connection into a network.

__Link to detailed interface description:__ 

* link:https://ersa.atlassian.net/wiki/spaces/IC/pages/1854996481/mDNS+Communication[MDNS]
* link:https://ersa.atlassian.net/wiki/spaces/IC/pages/1825243178/Ersa-Protocol[Ersa Protocol]
* link:https://ersa.atlassian.net/wiki/spaces/IC/pages/2200207461/Bluetooth[Bluetooth]

[#Interface_etcUI]
*[.underline]#Interface etcUI#*

The **etcUI** interface is responsible for the user interaction via browser to control the i-Con Trace Device.

__Link to detailed interface description:__ 

* link:++file:///L:/TDWEB/TDWeb_EPM/Software/TRACE-Cockpit/Offizielle Releases - Ersa TRACE Cockpit/++[ETC Releases] / i-Con Trace - find the manual within every release

[#Interface_etcNetwork]
*[.underline]#Interface etcNetwork#*

As the <<Component_ETC_Application>> runs on a server the normal network interface is limited to LAN.
From the networks perspective it doesn't make any difference anyway.

[#Interface_brokerNetwork]
*[.underline]#Interface brokerNetwork#*

As the <<Component_MQTT_Broker>> runs on a server the normal network interface is limited to LAN.
From the networks perspective it doesn't make any difference anyway.

== System use cases

include::excel\system_use_case_diagrams_overview.xlsx\overview.adoc[]

=== Use case - Initialization

==== Use case - Initialization - i-Con Trace with factory settings without an ethernet board attached

plantuml::system_use_cases\initialization\sequence-system-use_cases_initialization.puml["Sequence-use-cases-initialization",format=svg]

==== Use case - Initialization - i-Con Trace with factory settings with an ethernet board attached

plantuml::system_use_cases\initialization\sequence-system-use_cases_initialization_ethernet.puml["Sequence-use-cases-initialization-ethernet",format=svg]

==== Use case - Initialization - i-Con Trace with factory settings without an ethernet board attached and no device will connect

plantuml::system_use_cases\initialization\sequence-system-use_cases_initialization_no_connection.puml["Sequence-use-cases-initialization-no-connection",format=svg]

=== Use case - Usage

==== Use case - Usage - Connection setup (BLE)

plantuml::system_use_cases\initialization\sequence-system-use_cases_initialization.puml["Sequence-use-cases-initialization",format=svg]

==== Use case - Usage - already configured and available MQTT Broker Mobile App (configuration of soldering station and logging of telemetry data) (MQTT)

plantuml::system_use_cases\usage\sequence-system-use_cases_connect_to_MA_with_available_MQTT_Broker.puml["Sequence-use-cases-usage-already-configured-and-available-broker_MA",format=svg]

==== Use case - Usage - already configured but unavailable MQTT Broker Mobile App (WLAN/LAN - ERSA)

plantuml::system_use_cases\usage\sequence-system-use_cases_connect_to_MA_with_unavailable_MQTT_Broker.puml["Sequence-use-cases-usage-already-configured-and-unavailable-broker_MA",format=svg]

==== Use case - Usage - Usage in mixed operation (mobile App and ETC (WLAN/LAN - ERSA))

plantuml::system_use_cases\usage\sequence-system-use_cases_usage_mixed_MA_and_ETC.puml[Sequence-use-cases-usage-in-mixed-operation",format=svg]

==== Use case - Usage - ESP Firmware update (WLAN/LAN - ERSA)

plantuml::system_use_cases\usage\sequence-system-use_cases_usage_mobile_app_firmware_update.puml["Sequence-use-cases-usage-ESP-update",format=svg]

==== Use case - Usage - initialization/configuration of MQTT Broker using mdns (WLAN/LAN - ERSA)

plantuml::system_use_cases\usage\sequence-system-use_cases_initialization_configuration_of_MQTT_Broker_using_mdns.puml["Sequence-use-cases-usage-init-via-mdns",format=svg]

==== Use case - Usage - initialization/configuration of MQTT Broker using ersa protocol (WLAN/LAN - ERSA)

plantuml::system_use_cases\usage\sequence-system-use_cases_initialization_configuration_of_MQTT_Broker_using_ersa_protocol.puml["Sequence-use-cases-usage-init-via-ersaprot",format=svg]

==== Use case - Usage - already configured and available MQTT Broker ETC (configuration of soldering station and logging of telemetry data) (MQTT)

plantuml::system_use_cases\usage\sequence-system-use_cases_connect_to_ETC_with_available_MQTT_Broker.puml["Sequence-use-cases-usage-already-configured-and-available-broker_ETC",format=svg]

==== Use case - Usage - already configured but unavailable MQTT Broker ETC (WLAN/LAN - ERSA)

plantuml::system_use_cases\usage\sequence-system-use_cases_connect_to_ETC_with_unavailable_MQTT_Broker.puml["Sequence-use-cases-usage-already-configured-and-unavailable-broker_ETC",format=svg]

==== Use case - Usage - Firmware Update (WLAN/LAN - ERSA)

plantuml::system_use_cases\usage\sequence-system-use_cases_usage_firmware_update_Wlan_Lan_Ersa.puml["Sequence-use-cases-usage-firmware-update_ETC",format=svg]

== Subsystems

=== Subsystem i-Con Trace Device

include::subsystems_i-Con_Trace_Device/subsystem_i-Con_Trace_Device.adoc[]