@startuml FindFourCornerMatchProcess
scale 300 width
skinparam padding 10
skinparam nodesep 60
!define DARKBLUE #0000A0
!define DARKGREEN #008000
!define DARKORANGE #FF8C00
!define DARKRED #FF0000

participant WorkflowManagerHR600Base
participant FindFourCornerMatchWorkflowStepAdditionalViewModel
participant FindFourCornerMatchWorkflowStepViewModel
participant BigBGAManagerHR600Base
participant ImageProcessingManagerHR600Base
participant MotionControlManagerHR600Base

WorkflowManagerHR600Base --> WorkflowManagerHR600Base : toFindFourCornerMatch\n
activate WorkflowManagerHR600Base
WorkflowManagerHR600Base --> BigBGAManagerHR600Base : Init FindFourCornerMatchStateMachine\n
activate BigBGAManagerHR600Base
BigBGAManagerHR600Base --> FindFourCornerMatchWorkflowStepAdditionalViewModel : Return Result\n
loop until virtual Best Match is Ok
  FindFourCornerMatchWorkflowStepAdditionalViewModel --> BigBGAManagerHR600Base : Virtual Correction\n
  activate BigBGAManagerHR600Base
  BigBGAManagerHR600Base --> MotionControlManagerHR600Base : Correction drive X,Y and Phi\n
  activate MotionControlManagerHR600Base
  MotionControlManagerHR600Base --> BigBGAManagerHR600Base : Return Result\n
  deactivate MotionControlManagerHR600Base
  BigBGAManagerHR600Base --> ImageProcessingManagerHR600Base : Excecute Algorithm FourCornerMatch\n
  activate ImageProcessingManagerHR600Base
  ImageProcessingManagerHR600Base --> BigBGAManagerHR600Base : Return Result\n
  deactivate ImageProcessingManagerHR600Base
  BigBGAManagerHR600Base --> FindFourCornerMatchWorkflowStepViewModel : Return Result\n
  deactivate BigBGAManagerHR600Base
end loop

FindFourCornerMatchWorkflowStepAdditionalViewModel --> BigBGAManagerHR600Base : Undo all\n
activate BigBGAManagerHR600Base
  note right
  Undo all action will reset to first found best match
  end note
BigBGAManagerHR600Base --> FindFourCornerMatchWorkflowStepAdditionalViewModel : Return Result\n
deactivate BigBGAManagerHR600Base

note right of MotionControlManagerHR600Base 
  End point motion control
end note

note right of ImageProcessingManagerHR600Base 
  End point image 
  processing control
end note

note left of WorkflowManagerHR600Base 
  End point of main workflow 
  FindFourCornerMatchProcess
  Returns to next main Step
end note

note right of BigBGAManagerHR600Base 
  Processing Base for 
  BigGBA Workflow
end note

note right of FindFourCornerMatchWorkflowStepAdditionalViewModel 
  SideBar View
  FindFourCornerMatchProcess
end note

note right of FindFourCornerMatchWorkflowStepViewModel 
  Main View
  FindFourCornerMatchProcess
end note

footer == End of FindFourCornerMatchProcess Diagram ==

@enduml