@startuml FourCornerPinDetection
skinparam padding 10
skinparam nodesep 60
!define DARKBLUE #0000A0
!define DARKGREEN #008000
!define DARKORANGE #FF8C00
!define DARKRED #FF0000
WorkflowManagerHR600Base:toFourCornerPinDetection --> CreateFourCornerPinDetectionViewModell : new CreateFourCornerPinDetectionViewModell\n
WorkflowManagerHR600Base:toFourCornerPinDetection --> CreateFourCornerPinDetectionAdditionalViewModell : new CreateFourCornerPinDetectionAdditionalViewModell\n
WorkflowManagerHR600Base:toFourCornerPinDetection --> BigBGAManager : new BigBGAManager\n

@enduml