@startuml
[*] --> Undefined

state Undefined {
    [*] --> Undefined
    Undefined --> SelectProfile : NextStep
    Undefined --> PcbVerification : StartMesProzess
}

state PcbVerification {
    PcbVerification --> VerifyPcb : StartMesProzess\n[IsPcbVerificationFinished]
    PcbVerification --> CanceledWorkflow : CancelRework
}

state VerifyPcb {
    VerifyPcb --> Reference : NextStep\n[IsVerifyPcbFinished]
    VerifyPcb --> VerifyPcb : StartMesProzess
    VerifyPcb --> CanceledWorkflow : CancelRework
}

state SelectProfile {
    SelectProfile --> AdjustPcb : NextStep\n[IsAlreadyReferenced\nProfileSelected\nExtendedHeatersActive]
    SelectProfile --> PrepareScavenging : NextStep\n[IsAlreadyReferenced\nScavengerIsActive\nScavengingSelected]
    SelectProfile --> AdjustCrosshair : NextStep\n[IsAlreadyReferenced\nIsDesolderSelected\nProfileSelected\nPcbFrameInLockPosition]
    SelectProfile --> PreparePickUpFromTray : NextStep\n[IsAlreadyReferenced\nIsBigComponentSelected\nIsPlacementSelected\nPcbFrameInLockPosition\nProfileSelected]
    SelectProfile --> ChangePipetteBeforePipetteDip : NextStep\n[IsAlreadyReferenced\nIsPlacementSelected\nIsPinTransferSelected\nProfileSelected\nPcbFrameInLockPosition]
    SelectProfile --> ProvideComponent : NextStep\n[IsAlreadyReferenced\nIsCyclicWorkflowMode\nPcbFrameInLockPosition]
    SelectProfile --> PrepareProvideComponent : NextStep\n[IsAlreadyReferenced\nIsPlacementSelected\nProfileSelected\nPcbFrameInLockPosition]
    SelectProfile --> Inspection : NextStep\n[IsAlreadyReferenced\nIsInspectionSelected\nProfileSelected\nPcbFrameInLockPosition]
    SelectProfile --> AdjustPcbForSolder : NextStep\n[IsAlreadyReferenced\nIsSolderSelected\nProfileSelected\nExtendedHeatersActive]
    SelectProfile --> AdjustCrosshairForSolder : NextStep\n[IsAlreadyReferenced\nIsSolderSelected\nProfileSelected\nPcbFrameInLockPosition]
    SelectProfile --> InspectionAfterSolder : NextStep\n[IsAlreadyReferenced\nIsInspectionAfterSolderSelected\nProfileSelected\nPcbFrameInLockPosition]
    SelectProfile --> Reference : NextStep\n[ProfileSelected]
    SelectProfile --> VerifyPcb : StartMesProzess\n[IsPcbVerificationFinished]
    SelectProfile --> InsertScavengingPipette : NextStep\n[ScavengingSelected\nProfileSelected\nIsAlreadyReferenced]
}

state Reference {
    Reference --> ProvideComponent : NextStep\n[IsReferenceFinished\nIsCyclicWorkflowMode\nPcbFrameInLockPosition]
    Reference --> AdjustPcb : NextStep\n[IsReferenceFinished\nExtendedHeatersActive]
    Reference --> PrepareScavenging : NextStep\n[IsReferenceFinished\nScavengerIsActive\nScavengingSelected]
    Reference --> AdjustCrosshair : NextStep\n[IsReferenceFinished\nIsDesolderSelected\nPcbFrameInLockPosition]
    Reference --> PreparePickUpFromTray : NextStep\n[IsReferenceFinished\nIsBigComponentSelected\nIsPlacementSelected\nPcbFrameInLockPosition]
    Reference --> ChangePipetteBeforePipetteDip : NextStep\n[IsReferenceFinished\nIsPlacementSelected\nIsPinTransferSelected\nPcbFrameInLockPosition]
    Reference --> PrepareProvideComponent : NextStep\n[IsReferenceFinished\nIsPlacementSelected\nPcbFrameInLockPosition]
    Reference --> Inspection : NextStep\n[IsReferenceFinished\nIsInspectionSelected\nPcbFrameInLockPosition]
    Reference --> AdjustPcbForSolder : NextStep\n[IsReferenceFinished\nIsSolderSelected\nExtendedHeatersActive]
    Reference --> AdjustCrosshairForSolder : NextStep\n[IsReferenceFinished\nIsSolderSelected\nPcbFrameInLockPosition]
    Reference --> InspectionAfterSolder : NextStep\n[IsReferenceFinished\nIsInspectionAfterSolderSelected\nPcbFrameInLockPosition]
    Reference --> VerifyPcb : NextStep
    Reference --> CanceledWorkflow : CancelRework
    Reference --> InsertScavengingPipette : NextStep\n[IsReferenceFinished\nScavengingSelected]
}

state AdjustPcb {
    AdjustPcb --> PrepareScavenging : NextStep\n[ScavengerIsActive\nScavengingSelected]
    AdjustPcb --> AdjustCrosshair : NextStep\n[IsDesolderSelected]
    AdjustPcb --> PreparePickUpFromTray : NextStep\n[IsBigComponentSelected\nIsPlacementSelected]
    AdjustPcb --> ChangePipetteBeforePipetteDip : NextStep\n[IsPlacementSelected\nIsPinTransferSelected]
    AdjustPcb --> PrepareProvideComponent : NextStep\n[IsPlacementSelected]
    AdjustPcb --> Inspection : NextStep\n[IsInspectionSelected]
    AdjustPcb --> AdjustCrosshairForSolder : NextStep\n[IsSolderSelected]
    AdjustPcb --> InspectionAfterSolder : NextStep\n[IsInspectionAfterSolderSelected]
    AdjustPcb --> FinishRework : NextStep
    AdjustPcb --> CanceledWorkflow : CancelRework
    AdjustPcb --> VerifyPcb : StartMesProzess
}

state ProvideComponent {
    ProvideComponent --> PinDetection : NextStep\n[IsProvideComponentFinished\nIsDipComponentSelected]
    ProvideComponent --> PinDetection : NextStep\n[IsProvideComponentFinished]
    ProvideComponent --> CanceledWorkflow : CancelRework
    ProvideComponent --> VerifyPcb : StartMesProzess
}

state DipComponent {
    DipComponent --> PinDetection : NextStep\n[IsDipComponentFinished]
    DipComponent --> CanceledWorkflow : CancelRework
    DipComponent --> VerifyPcb : StartMesProzess
}

state PreparePickUpFromTray {
    PreparePickUpFromTray --> PickUpFromTray : NextStep\n[IsPreparePickUpFromTrayFinished]
    PreparePickUpFromTray --> CanceledWorkflow : CancelRework
    PreparePickUpFromTray --> VerifyPcb : StartMesProzess
}

state PickUpFromTray {
    PickUpFromTray --> PrepareProvideComponent : NextStep\n[IsPickUpFromTrayFinished\nIsPlacementSelected\nIsBigComponentSelected]
    PickUpFromTray --> PreparePickUpFromTray : NextStep\n[IsPickUpFromTrayFinished\nIsBigComponentSelected]
    PickUpFromTray --> CanceledWorkflow : CancelRework
}

state FinishRework {
    FinishRework --> Reference : NextStep
    FinishRework --> Reference : RedoRework
    FinishRework --> SelectProfile : CancelRework
    FinishRework --> VerifyPcb : StartMesProzess
}

state CanceledWorkflow {
    CanceledWorkflow --> Undefined : Logout
    CanceledWorkflow --> Delegate : RedoLastStep
    CanceledWorkflow --> Reference : RedoRework
    CanceledWorkflow --> SelectProfile : CancelRework
    CanceledWorkflow --> VerifyPcb : StartMesProzess
}

@enduml